module.exports = {
    LEVEL_INFO: "INFO",
    LEVEL_ERROR: "ERROR",
    LEVEL_DEBUG: "DEBUG",
    LEVEL_FATAL: "FATAL",
    LEVEL_WARNING: "WARNING",

    TYPE_SYNC_START: "SYNC START",
    TYPE_SYNC_END: "SYNC FINISHED",
    TYPE_ISSUE: "ISSUE",
    TYPE_LINK: "LINK",
    TYPE_INSERT_UPDATE: "INSERT UPDATE",
    TYPE_MARK_REMOVE_START: "MARK REMOVED START",
    TYPE_MARK_REMOVE_END: "MARK REMOVED FINISHED",
    TYPE_MARK_REMOVED: "MARK REMOVED",
    TYPE_DB_CONNECTION: "DATABASE CONNECTION",
    TYPE_UPDATE_NOTIFICATION: "NUMBER OF UPDATES",
    TYPE_INSERT_NOTIFICATION: "NUMBER OF INSERTS",
    TYPE_DELETE_NOTIFICATION: "NUMBER OF DELETES",
    TYPE_SYNC_DATA_FETCH: "REQUESTING DATA TO SYNC"
};
